apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- frontend/deploy.yml
- backend/service.yml
- frontend/service.yml

images:
- name: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/backend
  newName: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/backend
  newTag: 9b4140b3b8af1a8c19dabe6cf658df00b2185eea
- name: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/frontend
  newName: 381491977261.dkr.ecr.us-east-1.amazonaws.com/workshop-na-nuvem/production/frontend
  newTag: 3858ffb7b3a3bab984eebbc3e0f77e8e286cac35
